### ISSUE TITLE
npm start doesnt works

### ISSUE THREAD

**Issue by matti377** [TerbiumOS/webOS#30]
Deployed in on ubuntu server, everything worked up until npm start. I get this error:
 $npm start

> uv-app@1.0.0 start
> node index.js

/home/vpsadmin/webOS/node_modules/@tomphttp/bare-server-node/dist/BareServer.js:50
        init.logErrors ??= false;
                        ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/vpsadmin/webOS/node_modules/@tomphttp/bare-server-node/dist/createServer.js:5:41)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by Xtendera** [comment]
What node version are you on?

**Comment by Notplayingallday383** [comment]
Did you run npm install?
